### ISSUE TITLE
Name suggestion for `detect` event

### ISSUE THREAD

**Issue by larsblumberg** [nathankunicki/nuimojs#1]
Hi Nathan! Lars from Senic here. This is great NodeJS lib for Nuimo, we're happy to see those libs emerging.

I had one suggestion: For me it sounds like `detect` event should be named `distance` instead as `detect` is a little too generic. This event reports the _distance_ of the users hand from Nuimo.

**Comment by nathankellenicki** [comment]
Fair point, thanks Lars! I've just pushed a small update which includes this as well as a few other additions (Notably, addition of seperate events for flying and swiping directions).
