### ISSUE TITLE
Feature request: on("disconnect", callback(device))

### ISSUE THREAD

**Issue by mrothenbuecher** [nathankunicki/nuimojs#10]
Feature request: on("disconnect", callback(device))

Would something like this possible?

**Comment by mAPBhlJ** [comment]
Interesting function, though I'm not sure if it is possible.
Does the other libraries from Senic/Nuimo have this?

As far as I know,
BLE works in a manner that the device can be in a "low power" state and thus does not send any info. If the device were to lose connection (power off or out of range) it will have to possibility to transmit this.

You may be able to send an empty matrix and check if it leads to an error (that should indicate the device is out of range/off). But I'm not sure if this library will throw such an error.

**Comment by nathankellenicki** [comment]
Hi, apologies for the late response. This has now been implemented, as an event on the Device object itself. (deviceObj.on("disconnect", callback())

(@Paul-Ver, indeed, the Noble library I use does support a disconnect event. :))
