### ISSUE TITLE
Get RSSI (connection strength)

### ISSUE THREAD

**Issue by mAPBhlJ** [nathankunicki/nuimojs#11]
How could I get the RSSI value (connection strength)?

I'd like to set up the Nuimo with multiple bluetooth accespoints and would like to triangulate the position and/or connect to the strongest/closest accespoint.

**Comment by nathankellenicki** [comment]
Hi, thanks for the feedback!

I've implemented this feature in 0.2.0. The device now has a "rssi" property, and there is now a "rssiChange" event.
