### ISSUE TITLE
Manually disconnect a device

### ISSUE THREAD

**Issue by mAPBhlJ** [nathankunicki/nuimojs#13]
For my project, it could happen that one Nuimo is connected to multiple "gateways".
The central server will identify this problem and then tell one of the gateways to disconnect the Nuimo.

The library needs to be able to disconnect one of the Nuimo's, (hopefully) based on the UUID.

Adding:
```
    disconnect(){
        this._peripheral.disconnect();
    }
```
To device.js makes it possible to disconnect a Nuimo after the `nuimo.on("discover", (device) => {`

Should I keep track of which Nuimo's are connected to my "gateway"* or is there an easy way to disconnect a device based on the UUID?
I can't seem to find the link between the UUID and actual device.

Something along the lines of: `Nuimo.disconnect(uuid)` or `Nuimo.getDevice(uuid)` will work.

*can this library actuallly handle multiple Nuimos? (I've got only one to test atm)

**Comment by jo-me** [comment]
Hey there, 
maybe you can simplify your scenario by changing your approach a little bit so that you only have one gateway connected to the nuimo and several clients connected to the gateway. 
Have a look here: https://github.com/wind-rider/nuimo-mqtt-manager
I have not tested this personally, though. Maybe a simple nodejs REST api could do a similar thing. That way not every component needs to care about Nuimo's implementation details.

**Comment by mAPBhlJ** [comment]
Well, the actual problem is that once I power up the Nuimo, it can connect to two different gateways,.

If it does, I'd like to disconnect it from one of the gateways (though, currently I can't disconnect them based on UUID).

**Comment by nathankellenicki** [comment]
@Paul-Ver Indeed a manual disconnect option is probably a good idea!

Currently the nuimojs library doesn't keep track of what devices it has discovered after emitting the "discover" event with the device object attached. This means that there would need to be a LUT implemented somewhere to keep track of them (Which isn't non trivial).

If the device object itself had a disconnect method, would that suffice? If you were to keep track of them, there is a uuid attribute on the device object you could use (https://github.com/nathankunicki/nuimojs/blob/master/src/device.js#L99).

If you need/would prefer a "getDeviceByUUID method, I can have a look at this.

**Comment by nathankellenicki** [comment]
@Paul-Ver I see your use case. I have the same issue, and I handle it by keeping track of what UUID's are allowed on each gateway on a higher level. After the discovery is made, I make the decision on whether to connect or not based on the UUID whitelist. (Using the UUID attribute on the device mentioned above)

**Comment by nathankellenicki** [comment]
See this for a WIP of your request: https://github.com/nathankunicki/nuimojs/commit/0fe3f39f3da30883ab551d478b324b2b7207a10b

**Comment by mAPBhlJ** [comment]
Great that you're helping out! I only don't see how the UUID relates to the "device" object.
Is it possible to get the UUID in nuimo.js "device._peripheral.on("connect", () => {"?

If so, we could efficiently store the device and UUID in a object [like this](https://github.com/Paul-Ver/nuimojs/commit/c3675c8ae97a03e354ad935632c5027354609925).

The whitelist/blacklist thing is a whole other issue, indeed useful.
But in my usecase I want to connect them (check RSSI) and disconnect them later.
It's also a problem if I don't want to explicitly whitelist them but just don't want one Nuimo to connect to multiple gateways.

**Comment by nathankellenicki** [comment]
The UUID relates to the device instance in that there is a one-to-one mapping between it and the peripheral. The unlying peripheral should be invisible to the end user (Damn you Javascript and your lack of private methods!)

In any event, your code is almost the same as mine except I like yours better - using an object as a hash table like means less array iteration. It's just a bit more elegant. :)

I'll merge it in and add the manual disconnect I put in my branch.

**Comment by nathankunicki** [comment]
...that is if you want to PR it against mine. :)

**Comment by nathankellenicki** [comment]
Added in https://github.com/nathankunicki/nuimojs/pull/15
