### ISSUE TITLE
Whitelist/Blacklist

### ISSUE THREAD

**Issue by mAPBhlJ** [nathankunicki/nuimojs#14]
It would be useful if the user can choose to allow a list of UUID's that are in a whitelist.
Or if the user can choose to block UUID's that are in a blacklist.

I'm not sure if this should be handled in the library, since an user can easily choose to (or not to) connect a Nuimo whenever it is discovered.

Though, it makes sense in combination with the disconnect, you should be able to blacklist it (or remove from whitelist), so it won't automatically reconnect.

The programming for this will be trivial, we could add this on the discovery of a device:

```
class Nuimo extends EventEmitter {

    constructor (whitelist = false) { //Note fancy default value in constructor
        super();
        this.useWhiteList = whitelist;
        this.whiteList = [];
        this.blackList = [];
    }



if(this.useWhitelist){
   if(this.whiteList.includes(uuid){//Note fancy array.includes
      //connect
   }
}else{
   if(!this.blackList.includes(uuid){
      //connect
   }
}
//not connect (if doesn't match any statement above).
```

I think using a whitelist and blacklist at the same time would also be a bit weird (what's the use of a blacklist if you block everything on default (with a whitelist)).
We could probably get away with using one "list" (be it a blacklist or whitelist) but I think it was a little more clearer by separating them.

**Comment by nathankellenicki** [comment]
Yes, in fact I remembered this other project I use (https://github.com/hortinstein/node-dash-button) where they implement a whitelist by passing in an array of mac addresses to the constructor. I think I'll implement it similarly.

**Comment by nathankellenicki** [comment]
Implemented whitelist in https://github.com/nathankunicki/nuimojs/pull/16. Not entirely sure a blacklist is necessary, it seems the use case is quite limited, and if you really need it you can check on the discovery?

**Comment by mAPBhlJ** [comment]
Positive, I could indeed check on discovery.
But you could say the same goes for whitelist.
For my application it's can be useful to allow the device on default, until some gets annoyed by it (and can choose to block a device for that node).

Given the implementation of the whitelist, it'd be easy to come up with my own blacklist implementation, if necessary. Or just request the server if the Nuimo may/may not connect on discovery.

If anyone feels that we still need a blacklist, you're open to reopen this issue, or create one specific for the blacklist. And/or create a pull request with said functionality.
