### ISSUE TITLE
Tested on Windows 10 :D

### ISSUE THREAD

**Issue by mAPBhlJ** [nathankunicki/nuimojs#17]
I've made the library work on my Windows 10 laptop.
(clearly not an Apple device ;D)

See here: https://youtu.be/iqz6Pl6ZYus (sorry for the vertical filming, was hard to hold the phone and play around with the Nuimo at the same time).

If you feel the need, you could update it in the readme, but you might not, since it's quite a bit more steps to get it working in Windows, but I'll list my steps, for future reference.

I'm using a [Bluetooth 4.0 USB dongle](http://www.replacedirect.nl/product/p0119661/trust-bluetooth-40-usb-adapter.html), since I don't want to overwrite the drivers of my onboard bluetooth (it's on my WiFi chip), and I use Windows 10 as OS.

1. I had a problem with my Python version being too high to be able to build the bluetooth HCI library. I resolved this by installing an older version of Python (2.7), changing my path to the 2.7 installation folder and restarting my PC.
2. I had a problem with VCBuild.exe not being found. I installed[ dotNet framework 4](https://www.microsoft.com/en-us/download/details.aspx?id=8279) and rebooted once again.
3. Eventually I could install Nuimojs (with the optional dependencies for Windows)

4. I got a crash when running the library: "no USB bluetooth 4.0 compatible device found" (or something like that). Obviously I plugged in a USB Bluetooth 4.0 dongle.

5. Now I got a crash with the message: "LIBUSB_ERROR_NOT_SUPPORTED", I resolved this by using  [libusb-win32](http://www.libusb.org/wiki/libusb-win32), and running "bin/amd64/install-filter-win.exe" and selecting my USB bluetooth dongle.

6. After that it would work, but randomly crash. But I resolved [this way](https://github.com/tessel/node-usb/issues/155)

I hope this helps anyone :)

I think you're awesome for creating and sharing this library 👍
It's extremely easy to use and "cross platform" :D

Now I don't have to get into swift, or Windows Universall App and something else for Linux or raspberry.
One simple codebase, with all the functions needed :)

**Comment by nathankellenicki** [comment]
Sorry I didn't get to this until now! Thanks for testing this, it's great that there's now these instructions!

I'm going to add something to the readme saying it has been tested on Windows 10, with a link to this issue for people who need help installing the Noble dependencies.

Thanks again!
