### ISSUE TITLE
Multiple Nuimo's?

### ISSUE THREAD

**Issue by mAPBhlJ** [nathankunicki/nuimojs#18]
Does the library provide the possibility to use multiple Nuimo's on a single gateway?
I'm trying to do so, but can't really figure out how to get it working.

Both connect when the other one isn't connected.
Is it supported by the library?

**Comment by mAPBhlJ** [comment]
If I do:

```
nuimo.on("connect", () => {
        console.log("Controller connected");
        nuimo.scan();
});

```

Both devices will attach.
I'm not if this is the intended way of connecting multiple Nuimo's (since it disables scanning when something is found), but it seems to work.

Please re-open this if this is not the intended way.

**Comment by nathankellenicki** [comment]
Sorry I didn't get around to this until now!

Yes, it seems like it would be an issue - especially as there was code introduced which stopped the scanning on discovery of a single device (https://github.com/nathankunicki/nuimojs/commit/5a2a555bedc0394320a2c86a79f92ac5bce239ce#diff-71028cd0c32802c365b1671466db4f2fR39). Unfortunately I don't have a second Nuimo to test!

Your solution is good, though it would be better if the Nuimo.js library itself handled this, so I think I might add the equivalent of this to happen automatically.

**Comment by nathankellenicki** [comment]
See latest version. :) Seems by default Noble won't discover any more devices after the first unless you stop/start scanning again. As you observed, connections are maintained.

**Comment by mAPBhlJ** [comment]
Seems to work like a charm!
Many thanks once again!
