### ISSUE TITLE
Noble 1.8 breaks nuimojs

### ISSUE THREAD

**Issue by mattwelch** [nathankunicki/nuimojs#20]
There are some rumblings in the issues in the `noble` repo, but the practical effect, as far as `nuimojs` is concerned, as that `noble` 1.8 prevents events (press, rotate, etc) from working on `nuimojs`. If I force `noble` version 1.7 in `package.json`, everything works fine.

**Comment by happycodelucky** [comment]
@mattwelch I just ran into this too. It looks like device.js should be using "data" notifications from `noble` instead of "read". See line 287 of device.js in `nuimojs`. 

I've added a pull request for the change

**Comment by nathankellenicki** [comment]
Thank you for the pull request, I've merged it. 👍
