### ISSUE TITLE
Module version mismatch

### ISSUE THREAD

**Issue by chbardel** [nathankunicki/nuimojs#22]
I installed your package via npm. I tried different versions of Node.js(LTS 6.10.2, 7.9.0), between which I can switch via Node Version Manager. However before installing these new versions and NVM I have installed Node.js 4.8.2 which is still installed and stated as "system" in NVM, when I list the installed versions.

The Error I get is as follows:
`/home/pi/node_modules/nuimojs/examples/info.js:1
(function (exports, require, module, __filename, __dirname) { let Nuimo = require("../nuimo.js"),
                                                              ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
`

And I get this one, when calling node with --use_strict:
`module.js:434
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 48.
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/pi/node_modules/nuimojs/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
`

I am specially curious if there is any solution for this without removing the old Nodejs version. I need that one for a Systemd Service I am running and have lots of packages installed. And I even cant upgrade it, because I have some old packages only supporting Node v4.x.

**Comment by nathankellenicki** [comment]
Well, that's tricky, because Nuimo.js is written in ECMAScript 6, which is only supported in v6 and above. Certain features are available in v4 with strict mode on (As you discovered), but it appears that the bluetooth-hci-socket module is perhaps incompatible with this version.

You may be able to use nvm to set different versions of Node for different users, and run certain services as one user, and others as another? Or, perhaps use nvm to install multiple versions and call the node binary explicitly by path when executing so multiple versions are in use at once.

**Comment by chbardel** [comment]
Thanks a lot! I am now calling the path explicitly and it works. I wasnt aware, that calling "node" with sudo overrides the version I choose in nvm. I was calling "node -v" without sudo all the time and thought I was using the right version, while in fact it was using the old one placed in the /usr/bin folder as soon as I stated sudo before it.

For longtime use I might switch to symbolic links in that folder, so that I dont have to call the path explicitly all the time.

**Comment by nathankellenicki** [comment]
Glad to hear you have a solution!
