### ISSUE TITLE
Does this work with nuimo click or Friends of Hue Smart Switch?

### ISSUE THREAD

**Issue by jespertheend** [nathankunicki/nuimojs#27]
I'm thinking of buying one but I'd like to know if I can interact with it through some sort of api/sdk first.
Also what isn't completely clear to me is if this sdk connects with the nuimo hub or if it uses the bluetooth functionality of the device that nuimojs is run on.

**Comment by nathankellenicki** [comment]
This connects directly via Bluetooth to the Nuimo (circular). It doesn't utilise the hub. My motivation for creating this project was to use a Raspberry Pi as a hub to connect to all my Nuimo's and control various devices in my house. The Nuimo Hub didn't exist at that point.

As for Nuimo Click, I'm afraid no, it doesn't support it. I don't own any Clicks or a Nuimo Hub.

**Comment by jespertheend** [comment]
Cool, thanks for the info! I suppose the nuimo click doesn't use BLE anyway, I think it uses a proprietary protocol or something. I believe even the official hub needs an extra dongle to receive the signal.
