### ISSUE TITLE
Cooperation with https://github.com/brendonparker/nuimo-client.js

### ISSUE THREAD

**Issue by hansmbakker** [nathankunicki/nuimojs#3]
Hi,

cool that you're making a node.js client for Nuimo :)

There is already another one around at https://github.com/brendonparker/nuimo-client.js - Have you looked at possibilities for cooperation there?

I created a typescript-based variant at https://github.com/wind-rider/typed-nuimo-client.js of that library since I wanted to work strongly typed. You can also have a look there :)

**Comment by nathankellenicki** [comment]
Hi, thanks for the reply! I didn't see that one until I was publishing this one, but I saw it afterwards. It does however do a few things I'm not keen on, namely the use of callbacks for what, in my opinion, should be events.

In my view callbacks are more appropriate for one shot responses, such as querying a database, or checking the status for something, or waiting for something to happen. When something is expected to happen more than once and when not explicitly requested, an event is more appropriate.

I do however like TypeScript, so if you wanted to work together on creating a TypeScript variant, I'd love to. :)
