### ISSUE TITLE
Devices powered off and back up don't fire "connect" event

### ISSUE THREAD

**Issue by devbobo** [nathankunicki/nuimojs#8]
G'day Nathan,

I'm in the process of writing a Nuimo plugin for Homebridge and I've come across an issue if a device is powered down and back up again.

The easiest way to demonstrate this behaviour is to add the following code to the bottom of `examples/interraction.js`...

```
setInterval(
    function() {
        nuimo.scan();
    },
    30000
);
```

Because my plugin will run all the time interacting with Homebridge/HomeKit, my plugin needs to be able to handle new devices and existing devices going out of range or running out of battery life and then reconnecting again.

For testing purposes, I've set this to 30 secs. After initially having the device powered up when I run the script. I power it down and then back up. The device is successfully `discovered` again and reconnected, but the `connect` event is never refired.

Cheers,

David

**Comment by devbobo** [comment]
I should also mention that the `connect` callback isn't called either, if one is provided.

**Comment by mAPBhlJ** [comment]
You shouldn't keep "spamming"  the nuimo.scan(); function.

```
scan()

Begins scanning for Nuimo devices.

stop()

Stops scanning for Nuimo devices.
```

**Comment by nathankellenicki** [comment]
Hi, apologies for the late response.

I believe this has been fixed in the latest release - devices should reconnect and continue when powered off and on again.

**Comment by craigdent** [comment]
Devbobo,

Did you ever get round to making a homebridge-nuimo platform?

I’m interested in using it if you did as haven’t had much luck finding a homebridge plugin for it

**Comment by craigdent** [comment]
This still active...?

**Comment by nathankellenicki** [comment]
@craigdent Well, no, it's not. :) You posted in a closed thread.

It's worth noting your topic has nothing to do with the issue you posted in. If you want a reply you might have better luck messaging the user you want to speak to.
